import { afterAll, expect, it } from 'vitest';
import { App, CliCredentialsStackSynthesizer, Stack } from 'aws-cdk-lib';
import { CloudAssembly } from 'aws-cdk-lib/cx-api';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { Template } from 'aws-cdk-lib/assertions';
import { getDeployment } from '../lib/config.js';
import { rolloutInfrastructure } from '../lib/releases/rollout-infrastructure.js';
import { hostSlotAuthority } from '../lib/host-slot-authority.js';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
afterAll(() => CloudAssembly.cleanupTemporaryDirectories());

it('permits only immutable CDK host templates through one narrowly passed CloudFormation role', () => {
  const config = { ...getDeployment('stockholm-ecs'), account: '000000000000' };
  const app = new App();
  const stack = new Stack(app, 'Authority', { env: { account: config.account, region: config.region },
    synthesizer: new CliCredentialsStackSynthesizer({ fileAssetsBucketName: 'test-assets' }) });
  const lambda = new Function(stack, 'Controller', { runtime: Runtime.NODEJS_24_X, handler: 'index.handler', code: Code.fromInline('exports.handler=async()=>{};') });
  rolloutInfrastructure(stack, lambda, config, true);
  const resources = Object.values(Template.fromStack(stack).toJSON().Resources) as any[];
  const statements = resources.filter(r => r.Type === 'AWS::IAM::Policy').flatMap(p => p.Properties.PolicyDocument.Statement);
  const action = (name: string) => statements.find(s => [s.Action].flat().includes(name));
  const write = action('cloudformation:UpdateStack');
  expect(write.Condition.StringEquals['cloudformation:TemplateUrl']).toHaveLength(3);
  expect(write.Condition.StringEquals['cloudformation:RoleArn']).toBeDefined();
  expect(write.Condition.StringEqualsIfExists).toBeUndefined();
  expect(action('cloudformation:DeleteStack').Resource).toEqual(expect.objectContaining({ 'Fn::Join': expect.any(Array) }));
  expect(action('ecs:RegisterTaskDefinition')).toBeUndefined(); expect(action('ec2:RunInstances')).toBeUndefined();
  expect(action('ssm:GetParameter')).toBeUndefined(); expect(action('s3:PutObject')).toBeUndefined();
  expect(action('iam:PassRole').Condition.StringEquals['iam:PassedToService']).toBe('cloudformation.amazonaws.com');
  const reads = statements.filter(s => [s.Action].flat().includes('ecs:DescribeServiceDeployments'));
  expect(JSON.stringify(reads)).toContain('service-deployment/');
  expect(JSON.stringify(reads)).toContain(`service/${config.resourceName}/${config.resourceName}-gateway`);
  const stops = statements.filter(s => [s.Action].flat().includes('ecs:StopServiceDeployment'));
  expect(JSON.stringify(stops)).toContain('service-deployment/');
  expect(JSON.stringify(stops)).toContain(`service/${config.resourceName}/${config.resourceName}-gateway`);
  const assembly = app.synth();
  const manifest = assembly.artifacts.find(a => a.manifest.type === 'cdk:asset-manifest')!;
  const files = Object.values(JSON.parse(readFileSync(join(assembly.directory, (manifest.manifest.properties as any).file), 'utf8')).files) as any[];
  const sources = files.filter(file => file.source.path.startsWith('asset.'));
  expect(sources).toHaveLength(3);
  expect(sources.every(file => existsSync(join(assembly.directory, file.source.path)))).toBe(true);
});
it('limits slot provisioning to the regional subnet/security group and two execution authorities', () => {
  const config = { ...getDeployment('stockholm-ecs'), account: '000000000000' };
  const stack = new Stack(new App(), 'Provisioner', { env: { account: config.account, region: config.region } });
  const hostRole = 'arn:aws:iam::000000000000:role/host', executionRole = 'arn:aws:iam::000000000000:role/daemon-execution';
  hostSlotAuthority(stack, config, { subnet: 'subnet-exact', security: 'sg-exact', hostRole, executionRole });
  const resources = Object.values(Template.fromStack(stack).toJSON().Resources) as any[];
  const statements = resources.filter(r => r.Type === 'AWS::IAM::Policy').flatMap(p => p.Properties.PolicyDocument.Statement);
  expect(statements.filter(s => [s.Action].flat().includes('iam:PassRole')).map(s => s.Resource)).toEqual([hostRole, executionRole]);
  const grants = statements.filter(s => [s.Action].flat().includes('ecs:RegisterTaskDefinition'));
  expect(grants).toHaveLength(1); expect(grants[0].Resource.every((r: string) => r.includes(`:task-definition/${config.resourceName}-network`))).toBe(true);
  expect(statements.some(s => [s.Action].flat().includes('ssm:SendCommand'))).toBe(false);
  const tagUpdate = statements.find(s => [s.Action].flat().includes('ec2:CreateTags') && s.Condition.StringEquals['aws:ResourceTag/Project']);
  expect(tagUpdate.Condition.StringEquals['aws:ResourceTag/aws:cloudformation:stack-name']).toHaveLength(3);
  const deregister = statements.find(s => [s.Action].flat().includes('ecs:DeregisterTaskDefinition'));
  expect(deregister.Resource).toBe('*');
  expect(deregister.Condition.StringEquals['aws:RequestedRegion']).toBe(config.region);
  expect(statements.find(s => [s.Action].flat().includes('ec2:DeleteLaunchTemplate')).Condition.StringEquals['aws:ResourceTag/GhostlineHostStack']).toHaveLength(2);
  expect(statements.find(s => [s.Action].flat().includes('ssm:GetParameters')).Resource).toContain('parameter/aws/service/bottlerocket/');
});
